CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no VARCHAR(40) NOT NULL UNIQUE,
    resume_name VARCHAR(120) NOT NULL,
    telegram VARCHAR(120) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    age_at_application VARCHAR(20) NOT NULL,
    birth_date VARCHAR(80) NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    job_title VARCHAR(160) NOT NULL,
    current_salary VARCHAR(100) NOT NULL,
    expected_salary VARCHAR(100) NOT NULL,
    bc_experience VARCHAR(100) NOT NULL,
    employment_status VARCHAR(100) NOT NULL,
    education_type VARCHAR(100) NOT NULL,
    school VARCHAR(200) NOT NULL,
    education_period VARCHAR(160) NOT NULL,
    passport_status VARCHAR(100) NOT NULL,
    visa_status VARCHAR(160) NOT NULL,
    interview_time VARCHAR(160) NOT NULL,
    start_time VARCHAR(160) NOT NULL,
    current_country VARCHAR(100) NOT NULL,
    preferred_country VARCHAR(100) NOT NULL,
    stage VARCHAR(30) NOT NULL DEFAULT 'new',
    possible_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
    resume_storage_key VARCHAR(500) NOT NULL,
    resume_original_filename VARCHAR(255) NOT NULL,
    resume_content_type VARCHAR(150) NOT NULL,
    resume_size BIGINT NOT NULL,
    privacy_policy_version VARCHAR(30) NOT NULL,
    consented_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_applications_stage_created ON applications(stage, created_at DESC);
CREATE INDEX idx_applications_telegram ON applications(telegram);

CREATE TABLE application_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    admin_account VARCHAR(120) NOT NULL,
    note VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notes_application ON application_notes(application_id, created_at DESC);
