CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    title VARCHAR(180) NOT NULL,
    category VARCHAR(40) NOT NULL,
    business_unit VARCHAR(120) NOT NULL,
    required_location VARCHAR(160) NOT NULL,
    work_mode VARCHAR(40) NOT NULL,
    salary_range VARCHAR(120),
    summary VARCHAR(1000) NOT NULL,
    responsibilities TEXT NOT NULL,
    requirements TEXT NOT NULL,
    bonus TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_jobs_status_category ON jobs(status, category);
