CREATE TABLE research_campaign (
    id BIGINT PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    terms_version VARCHAR(40) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO research_campaign (id, status, terms_version, updated_at)
VALUES (1, 'PAUSED', '2026-08-01', CURRENT_TIMESTAMP);

CREATE TABLE research_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_number VARCHAR(40) NOT NULL UNIQUE,
    source VARCHAR(30) NOT NULL,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    concern VARCHAR(30) NOT NULL,
    feedback VARCHAR(500) NOT NULL,
    wallet_network VARCHAR(20) NOT NULL,
    wallet_ciphertext VARCHAR(200) NOT NULL,
    wallet_nonce VARCHAR(80) NOT NULL,
    wallet_hash VARCHAR(64) NOT NULL UNIQUE,
    ip_hash VARCHAR(64) NOT NULL,
    request_context_hash VARCHAR(64) NOT NULL,
    terms_version VARCHAR(40) NOT NULL,
    consented_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE research_submission_scenes (
    submission_id BIGINT NOT NULL REFERENCES research_submissions(id) ON DELETE CASCADE,
    scene VARCHAR(30) NOT NULL,
    PRIMARY KEY (submission_id, scene)
);

CREATE INDEX idx_research_created ON research_submissions(created_at DESC);
CREATE INDEX idx_research_rating ON research_submissions(rating);
CREATE INDEX idx_research_concern ON research_submissions(concern);
CREATE INDEX idx_research_source ON research_submissions(source);
CREATE INDEX idx_research_scene ON research_submission_scenes(scene);
