CREATE TABLE website_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id VARCHAR(64) NOT NULL UNIQUE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    qualified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_seconds INTEGER NOT NULL DEFAULT 15,
    ip_address VARCHAR(64),
    entry_path VARCHAR(500),
    last_path VARCHAR(500),
    device_type VARCHAR(80),
    device_model VARCHAR(200),
    operating_system VARCHAR(200),
    browser_name VARCHAR(200),
    screen_resolution VARCHAR(100),
    device_language VARCHAR(80),
    device_timezone VARCHAR(120),
    user_agent VARCHAR(1000)
);

CREATE INDEX idx_website_visits_qualified_at ON website_visits (qualified_at);
CREATE INDEX idx_website_visits_operating_system ON website_visits (operating_system);
CREATE INDEX idx_website_visits_device_model ON website_visits (device_model);
